src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductsRepository::class)]
class Products
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]

    private ?int $id = null;
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(length: 200)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $Ref = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: 'integer')]
    private ?int $Prix = null;

    public function getId(): ?int
    {
        return $this->id;
    }
    

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getRef(): ?int
    {
        return $this->Ref;
    }

    public function setRef(int $Ref): self
    {
        $this->Ref = $Ref;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }
    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Products;

class CartController extends AbstractController
{
    #[Route('/cart', name: 'app_cart')]
    public function index(Request $request): Response
{
    // Retrieve the cart items from the session
    $cartItems = $request->getSession()->get('cart_items', []);

    // Create an array to store the cart items with quantity
    $cart = [];

    // Count the quantity of each item in the cart
    foreach ($cartItems as $itemId) {
        if (!isset($cart[$itemId])) {
            $cart[$itemId] = 0;
        }
        $cart[$itemId]++;
    }

    $totalPrice = 0;
    $entityManager = $this->getDoctrine()->getManager();
    $articles = $entityManager->getRepository(Products::class)->findBy(['id' => array_keys($cart)]);

    // Calculate the total price by iterating over the products and quantities in the cart
    foreach ($articles as $article) {
        $totalPrice += $article->getPrix() * $cart[$article->getId()];
    }

    return $this->render('cart/index.html.twig', ['articles' => $articles, 'cart' => $cart, 'totalPrice' => $totalPrice]);
}


    /**
     * @Route("/add/{id}", name="app_add")
     */
    public function add($id, Request $request)
    {
        // Retrieve the cart items from the session
        $cartItems = $request->getSession()->get('cart_items', []);

        // Add the new item to the cart items array
        $cartItems[] = $id;

        // Store the updated cart items in the session
        $request->getSession()->set('cart_items', $cartItems);

        // Redirect to the cart page
        return $this->redirectToRoute('app_cart');
    }
    /**
 * @Route("/delete/{id}", name="app_delete")
 */
public function delete($id, Request $request)
{
    // Retrieve the cart items from the session
    $cartItems = $request->getSession()->get('cart_items', []);

    // Find the index of the item to delete
    $index = array_search($id, $cartItems);

    // If the item is found, remove it from the cart items array
    if ($index !== false) {
        unset($cartItems[$index]);
    }

    // Store the updated cart items in the session
    $request->getSession()->set('cart_items', $cartItems);

    // Redirect back to the cart page
    return $this->redirectToRoute('app_cart');
}

} 

templates/cart/index.html.twig
{% extends 'base.html.twig' %} 
{% block title %}{% endblock %} 
{% block body %} 
{% include 'navbar.html.twig' %}
<div class="mb-3">
 
 <div class="example-wrapper">
<h1>Liste des produits</h1>
  <table class="table">
        <thead>
            <tr>

                <th>Name</th>
                <th>Referance</th>
                <th>Description</th>
                <th>Prix</th>
                <th>Image</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td> {{ article.name }}</td>
                <td> {{ article.ref }}</td>
                <td> {{ article.description }}</td>
                <td>{{ article.prix }}</td>
                <td><img src="images/{{ article.image }}" style="width:100px"></td>
                <td>Quantity: {{ cart[article.id] }}</td>
                <td><a href="add/{{article.id}}" class="btn btn-success">Add +</a></td>
                <td>
                            <a href="{{ path('app_delete', { 'id': article.id }) }}" class="btn btn-danger">Delete</a>
                        </td>
            </tr>
            <tr>
    <td colspan="6" class="text-right" class="font-weight-bold">Total: {{ totalPrice }} Dt</td>
</tr>
            {% endfor %}

           </tbody>
    </table>    
    <p><a href="/" class="btn btn-warning" >Home</a></p>
</div>
{% endblock %}